Fix false positive readability/braces warning for trailing comma on c…
cpplint/cpplint pull request #229
Opened 2023-09-01 03:24 UTC by jordancharest

…oncepts.

Currently a readability/braces error is triggered for C++20 concepts. This change ignores trailing semi-colons that follow concept definitions.

2023-09-01 03:29 UTC, jordancharest commented
CI failure
```
Traceback (most recent call last):
    File "setup.py", line 87, in <module>
      'lint': Lint
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 177, in setup
      return run_commands(dist)
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 193, in run_commands
      dist.run_commands()
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/home/runner/work/cpplint/cpplint/.tox/python3.7/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/home/runner/work/cpplint/cpplint/.eggs/pytest_runner-5.2-py3.7.egg/ptr.py", line 209, in run
      return self.run_tests()
    File "/home/runner/work/cpplint/cpplint/.eggs/pytest_runner-5.2-py3.7.egg/ptr.py", line 220, in run_tests
      result_code = __import__('pytest').main()
    File "/home/runner/work/cpplint/cpplint/.eggs/pytest-7.4.0-py3.7.egg/pytest/__init__.py", line 5, in <module>
      from _pytest._code import ExceptionInfo
    File "/home/runner/work/cpplint/cpplint/.eggs/pytest-7.4.0-py3.7.egg/_pytest/_code/__init__.py", line 2, in <module>
      from .code import Code
    File "/home/runner/work/cpplint/cpplint/.eggs/pytest-7.4.0-py3.7.egg/_pytest/_code/code.py", line 35, in <module>
      import pluggy
    File "/home/runner/work/cpplint/cpplint/.eggs/pluggy-1.3.0-py3.7.egg/pluggy/__init__.py", line 23, in <module>
      from ._manager import PluginManager, PluginValidationError
    File "/home/runner/work/cpplint/cpplint/.eggs/pluggy-1.3.0-py3.7.egg/pluggy/_manager.py", line 3, in <module>
      import importlib.metadata
  ModuleNotFoundError: No module named 'importlib.metadata'
  Error: ERROR: InvocationError for command /home/runner/work/cpplint/cpplint/.tox/python3.7/bin/python setup.py test (exited with code 1)
___________________________________ summary ____________________________________
Error: ERROR:   python3.7: commands failed
Error: Process completed with exit code 1.
```

2024-03-31 16:01 UTC, aaronliu0130 commented
Could you provide tests and an example to demonstrate?

2024-03-31 16:03 UTC, aaronliu0130 requested changes
Would you kindly write some tests? Also, I doubt that this would work on multi-line concepts. Maybe we could take some inspiration from structs' detection.

2024-05-14 16:47 UTC, wyatterp365 approved these changes

2024-09-10 22:45 UTC, aaronliu0130 commented
Closing in favor of #288.

2024-09-10 22:45 UTC, closed without merging