Remove IWYU False Positives From Other Namespaces
cpplint/cpplint pull request #273
Opened 2024-05-20 17:37 UTC by geoffviola

This PR removes the false positives from `_HEADERS_CONTAINING_TEMPLATES` that come from non `std` namespaces. Users of boost or other namespaces will no longer get false positives.

```c++
// Warn
set<int> blah1;
std::set<int> blah2;
::std::set<int> blah2;
  set<int> blah1;
  std::set<int> blah2;
  ::std::set<int> blah2;

//  NO WARN
foo.set<int>();
foo->set<int>();

boost::container::set<int> blah3;
blah::std::set<int> blah3;
my_std::set<int> blah3;
my_set<int> blah4;
coolset<int> blah5;
std::blah<int> blah6;
::set<int> blah7;
```

2024-05-20 17:38 UTC, geoffviola commented
Note that there is a regression for the example from https://github.com/cpplint/cpplint/pull/62. This might be OK, because an unqualified `map` should probably be flagged since it could come from `std`. Other workarounds include
1. Only warning if `std::` is present. This goes against a previous decision to warn on unqualified names.
2. Only flag if a comma is present in the template for templates that require multiple template types. The implementation would be a little bit more complicated. If the type name is long, it might go to the next line.
3. Warn on unqualified `map`. Users would could use `map` qualified from other namespaces.

2024-05-21 15:07 UTC, aaronliu0130 requested changes
We shouldn't introduce a regression. Locally defined classes should not be IWYU'd.

2024-05-22 15:07 UTC, geoffviola commented
> We shouldn't introduce a regression. Locally defined classes should not be IWYU'd.

Is there a preference on how we want to handle this? I'd like to have a simple check that is consistent. Right now the checks for `set` and `map` are customized. It would be great if they didn't need to be. For example, it's weird that those each have special rules, but `unordered_set` and `unordered_map` don't.

The current check for `map` prevents false positives from other `map` definitions by using a [fully qualified name](https://github.com/cpplint/cpplint/blob/22c0fe24e22e2050eb7961d40f4a172ff3285e11/cpplint.py#L6082)(i.e. `std::map`). This check goes against the [comment](https://github.com/cpplint/cpplint/pull/217#issuecomment-1407700227
) from before.

The problem specifically with the name `map` is that it can mean applying a function to a functor. The provided example, could be used to initialize a functor, `Foo`.
```c++
template <typename T>
struct Foo {
    T t;
};
template <typename T>
Foo<T> map(T t) {
    return Foo<T>{ t };
}
struct Bar {
};
auto res = map<Bar>();
```
That example, only has one template; but it would be reasonable to have multiple ones. One could be the functor. The other could be a function.

If we want to go down the route of applying the check against 2+ template arguments, there are a couple of options.
1. Check for at least one comma in the same line. This check would be sensitive to formatting and nested types.
2. Check for at least one comma across multiple lines. This check would be robust to formatting, but not nested types.
3. Parse the angle brackets across multiple lines at the appropriate level. This would be robust to formatting and nested types.

Another set of options would be to look for a declaration with the same name in the same file. If the declaration is present, the check would be ignored. That might be difficult due to the most vexing parse. Also, it would miss declarations in other files.

It seems like all the options have trade offs, but it would be good to have some clarity.

2024-05-22 16:56 UTC, geoffviola commented
I made a change such that `map` still requires that the name to be fully qualified. The comment looked wrong so I updated it. There isn't a regression, but `auto foo = map<int, int>();` won't warn.

2024-05-22 23:18 UTC, aaronliu0130 approved these changes
Looks great!

2024-05-22 23:19 UTC, merged

2024-05-22 23:19 UTC, aaronliu0130 commented
oops, forgot the changelog part...

2024-05-22 23:19 UTC, aaronliu0130 commented
Anyways, you don't need to force push here. We always squash on merge.